I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
WindowsError: [Error 32] The process cannot access the file because it is being used by another process

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\asher\Documents\renpy-7.3.2-sdk\renpy\bootstrap.py", line 314, in bootstrap
    renpy.main.main()
  File "C:\Users\asher\Documents\renpy-7.3.2-sdk\renpy\main.py", line 485, in main
    renpy.dump.dump(False)
  File "C:\Users\asher\Documents\renpy-7.3.2-sdk\renpy\dump.py", line 255, in dump
    os.rename(new, args.json_dump)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process

Windows-8-6.2.9200
Ren'Py 7.3.2.320
Doki Doki FSM 1.0
Tue Sep 24 08:51:30 2019
